artifact_location: file:///home/sweta/mtp_home_latest/mtp_home_latest/src/components/D:\mtp_home_latest\mtp_home_latest\mlruns/181829207345734836
creation_time: 1759742730859
experiment_id: '181829207345734836'
last_update_time: 1759742730859
lifecycle_stage: active
name: Financial_Sentiment_Pipeline
