name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'  # runs daily at 6:00 AM UTC

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run Unit Tests
      run: |
        pytest tests/ --maxfail=1 --disable-warnings -q

  docker-build-and-push:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t financial-sentiment-pipeline .

    - name: Push Docker Image
      run: |
        docker tag financial-sentiment-pipeline ${{ secrets.DOCKER_USERNAME }}/financial-sentiment-pipeline:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/financial-sentiment-pipeline:latest
